# Generated by Django 5.2.8 on 2025-11-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimmage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit',
            name='deity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
